version: '3'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}

# client2:
#   build:
#     context: .
#     dockerfile: Dockerfile
#   restart: unless-stopped
#   environment:
#     DISCORD_TOKEN: ${DISCORD_TOKEN_2}
# 

