version: '3'

services:
  postgresdb:
    image: postgres:14.1-alpine
    container_name: postgresdb
    restart: unless-stopped
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: discord_music_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  client:
    # image: docker_id/docker_hub_repo:tag
    build:
      context: ..
      dockerfile: .dockerenv/Dockerfile
    container_name: discord-music-client
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: your-token
      POSTGRES_DB: discord_music_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgresdb
      POSTGRES_PORT: 5432
    depends_on:
      - postgresdb

volumes:
  postgres-data:
    driver: local

