version: '3'

services:
    discord-postgres:
        image: postgres:14.1-alpine
        container_name: discord-postgresdb
        restart: unless-stopped
        ports:
            - 6543:5432
        environment:
            POSTGRES_DB: discord_bot
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data

    bots:
        # image: docker_id/docker_hub_repo:tag
        build:
            context: ..
            dockerfile: .dockerenv/Dockerfile
        container_name: discord-bots
        restart: unless-stopped
        depends_on:
            postgres:
                condition: service_started
        environment:
            POSTGRES_DB: discord_bot
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_HOST: discord-postgres
            POSTGRES_PORT: 5432
            MUSIC_BOT_TOKEN: your-music-token
            MUSIC_BOT_LOG_LEVEL: INFO # DEBUG, ERROR, WARN
            UTILITY_BOT_TOKEN: your-utility-token
            MUSIC_BOT_LOG_LEVEL: INFO
            REGISTER_SLASH_COMMANDS: true

volumes:
    postgres-data:
        driver: local
